export const mockChartResults = {
  totalrecordcount: 8565,
  aggregations: [
    {
      name: "collection",
      column: "collection",
      items: [
        {
          value: "/I_NS1_Tools/I_Jira_Product/",
          count: 2017,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_Product/",
        },
        {
          value: "/I_NS2_Google/I_GoogleDrives_official/",
          count: 953,
          $filtered: false,
          display: "/I_NS2_Google/I_GoogleDrives_official/",
        },
        {
          value: "/I_Google/I_GoogleDrives/",
          count: 951,
          $filtered: false,
          display: "/I_Google/I_GoogleDrives/",
        },
        {
          value: "/I_NS1_Tools/I_Loopio/",
          count: 764,
          $filtered: false,
          display: "/I_NS1_Tools/I_Loopio/",
        },
        {
          value: "/I_Extranet/I_CustomerSupport/",
          count: 583,
          $filtered: false,
          display: "/I_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Extranet/I_Overflow/",
          count: 536,
          $filtered: false,
          display: "/I_NS1_Extranet/I_Overflow/",
        },
        {
          value: "/I_NS1_Tools/I_Slack/",
          count: 493,
          $filtered: false,
          display: "/I_NS1_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 294,
          $filtered: false,
          display: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Tools/I_Confluence/",
          count: 258,
          $filtered: false,
          display: "/I_NS1_Tools/I_Confluence/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport/",
          count: 224,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 184,
          $filtered: false,
          display: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_Doc/",
          count: 168,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_Doc/",
        },
        {
          value:
            "/I_NS1_Extranet/I_filesystem_madcap_flare_only_api_net_FTP/",
          count: 152,
          $filtered: false,
          display:
            "/I_NS1_Extranet/I_filesystem_madcap_flare_only_api_net_FTP/",
        },
        {
          value: "/I_NS1_Internet/I_Github_doc_sba_angular/",
          count: 134,
          $filtered: false,
          display: "/I_NS1_Internet/I_Github_doc_sba_angular/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_SBA/",
          count: 101,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_SBA/",
        },
        {
          value: "/I_Tools/I_Github/",
          count: 86,
          $filtered: false,
          display: "/I_Tools/I_Github/",
        },
        {
          value: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide/",
          count: 79,
          $filtered: false,
          display: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide/",
        },
        {
          value: "/I_NS1_Internet/I_Sinequa/",
          count: 74,
          $filtered: false,
          display: "/I_NS1_Internet/I_Sinequa/",
        },
        {
          value: "/I_NS1_Google/I_GoogleDrives/",
          count: 68,
          $filtered: false,
          display: "/I_NS1_Google/I_GoogleDrives/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_QA/",
          count: 45,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_QA/",
        },
        {
          value: "/I_Archives/Prospects/",
          count: 40,
          $filtered: false,
          display: "/I_Archives/Prospects/",
        },
        {
          value: "/I_NS1_Intranet/I_Impact/",
          count: 37,
          $filtered: false,
          display: "/I_NS1_Intranet/I_Impact/",
        },
        {
          value: "/I_Extranet/I_University_Courses/",
          count: 26,
          $filtered: false,
          display: "/I_Extranet/I_University_Courses/",
        },
        {
          value: "/I_Salesforce/I_Opportunities/",
          count: 24,
          $filtered: false,
          display: "/I_Salesforce/I_Opportunities/",
        },
        {
          value: "/I_Archives/Customers/",
          count: 20,
          $filtered: false,
          display: "/I_Archives/Customers/",
        },
        {
          value: "/I_NS1_Intranet/I_SBA_github_Internal/",
          count: 20,
          $filtered: false,
          display: "/I_NS1_Intranet/I_SBA_github_Internal/",
        },
        {
          value: "/I_Salesforce/I_Accounts/",
          count: 16,
          $filtered: false,
          display: "/I_Salesforce/I_Accounts/",
        },
        {
          value: "/I_Apps/I_Training/",
          count: 16,
          $filtered: false,
          display: "/I_Apps/I_Training/",
        },
        {
          value: "/I_Competitors/Lucidworks.web/",
          count: 13,
          $filtered: false,
          display: "/I_Competitors/Lucidworks.web/",
        },
        {
          value: "/I_Competitors/IHSMarkit.web/",
          count: 12,
          $filtered: false,
          display: "/I_Competitors/IHSMarkit.web/",
        },
        {
          value: "/I_Archives/AvantVente/",
          count: 12,
          $filtered: false,
          display: "/I_Archives/AvantVente/",
        },
        {
          value: "/I_NS2_Tools/I_Slack/",
          count: 10,
          $filtered: false,
          display: "/I_NS2_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Extranet/I_Download.sinequa.com_Azure/",
          count: 10,
          $filtered: false,
          display: "/I_NS1_Extranet/I_Download.sinequa.com_Azure/",
        },
        {
          value: "/I_Extranet/I_University_Users/",
          count: 9,
          $filtered: false,
          display: "/I_Extranet/I_University_Users/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_IT/",
          count: 9,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_IT/",
        },
        {
          value: "/I_Archives/MS/",
          count: 9,
          $filtered: false,
          display: "/I_Archives/MS/",
        },
        {
          value: "/I_Competitors/twitter/",
          count: 9,
          $filtered: false,
          display: "/I_Competitors/twitter/",
        },
        {
          value: "/I_NS1_Extranet/I_PartnerCorner/",
          count: 8,
          $filtered: false,
          display: "/I_NS1_Extranet/I_PartnerCorner/",
        },
        {
          value: "/I_NS1_Video/I_Vimeo/",
          count: 8,
          $filtered: false,
          display: "/I_NS1_Video/I_Vimeo/",
        },
        {
          value: "/I_Salesforce/I_Projects/",
          count: 8,
          $filtered: false,
          display: "/I_Salesforce/I_Projects/",
        },
        {
          value: "/I_Extranet/I_CustomerSupport_GDPR_only/",
          count: 7,
          $filtered: false,
          display: "/I_Extranet/I_CustomerSupport_GDPR_only/",
        },
        {
          value: "/I_Intranet/I_Company_Facebook/",
          count: 6,
          $filtered: false,
          display: "/I_Intranet/I_Company_Facebook/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport_GDPR_only/",
          count: 5,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport_GDPR_only/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport/[",
          count: 5,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport/[",
        },
        {
          value: "/I_NS2_Tools/I_Jira_Doc/",
          count: 5,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_Doc/",
        },
        {
          value: "/I_Extranet/I_ADFS/",
          count: 5,
          $filtered: false,
          display: "/I_Extranet/I_ADFS/",
        },
        {
          value: "/I_NS2_Tools/I_Jira_SBA/",
          count: 5,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_SBA/",
        },
        {
          value: "/I_Salesforce/I_Contacts/",
          count: 5,
          $filtered: false,
          display: "/I_Salesforce/I_Contacts/",
        },
        {
          value: "/I_Salesforce/I_BusinessCases/",
          count: 4,
          $filtered: false,
          display: "/I_Salesforce/I_BusinessCases/",
        },
        {
          value: "/I_U1_NS1_Extranet/I_Overflow/",
          count: 4,
          $filtered: false,
          display: "/I_U1_NS1_Extranet/I_Overflow/",
        },
        {
          value: "/I_U1_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 4,
          $filtered: false,
          display: "/I_U1_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Competitors/Lucidworks.web/",
          count: 3,
          $filtered: false,
          display: "/I_NS1_Competitors/Lucidworks.web/",
        },
        {
          value: "/I_Salesforce/I_Partners/",
          count: 3,
          $filtered: false,
          display: "/I_Salesforce/I_Partners/",
        },
        {
          value: "/I_Salesforce/I_Subscriptions/",
          count: 3,
          $filtered: false,
          display: "/I_Salesforce/I_Subscriptions/",
        },
        {
          value: "/I_NS1_Salesforce/I_Contacts/",
          count: 2,
          $filtered: false,
          display: "/I_NS1_Salesforce/I_Contacts/",
        },
        {
          value: "/I_NS1_Extranet/I_University_Courses/",
          count: 2,
          $filtered: false,
          display: "/I_NS1_Extranet/I_University_Courses/",
        },
        {
          value: "/I_NS1_Tools/I_Github/",
          count: 2,
          $filtered: false,
          display: "/I_NS1_Tools/I_Github/",
        },
        {
          value:
            '/I_NS1_Extranet/I_CustomerSupport/[…]insight_query_ns2","text":"11.8.1.2060"}',
          count: 2,
          $filtered: false,
          display:
            '/I_NS1_Extranet/I_CustomerSupport/[…]insight_query_ns2","text":"11.8.1.2060"}',
        },
        {
          value: "/I_Extranet/I_University_Programs/",
          count: 2,
          $filtered: false,
          display: "/I_Extranet/I_University_Programs/",
        },
        {
          value: "/I_Archives/ARD/",
          count: 2,
          $filtered: false,
          display: "/I_Archives/ARD/",
        },
        {
          value: "/I_Tools/I_Slack/",
          count: 2,
          $filtered: false,
          display: "/I_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Salesforce/I_Connectors/",
          count: 1,
          $filtered: false,
          display: "/I_NS1_Salesforce/I_Connectors/",
        },
        {
          value: "/I_NS2_Tools/I_Jira_QA/",
          count: 1,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_QA/",
        },
        {
          value: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide_NF_Official/",
          count: 1,
          $filtered: false,
          display: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide_NF_Official/",
        },
        {
          value: "/I_Salesforce/I_Connectors/",
          count: 1,
          $filtered: false,
          display: "/I_Salesforce/I_Connectors/",
        },
        {
          value: "/I_NS1_Salesforce/I_BusinessCases/",
          count: 1,
          $filtered: false,
          display: "/I_NS1_Salesforce/I_BusinessCases/",
        },
        {
          value: "/I_Tools/I_Jira_Product/",
          count: 1,
          $filtered: false,
          display: "/I_Tools/I_Jira_Product/",
        },
        {
          value: "/I_NS2_Tools/I_Jira_IT/",
          count: 1,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_IT/",
        },
      ],
      formats: null,
      $cccount: 10,
      $filtered: [],
      $remainingFiltered: [],
    },
  ],
  records: [],
  details: {
    statement:
      "select distribution('collection,ORDER=freqdesc,COUNT=100') as collection from insight_audit_index where timestamp BETWEEN '2022-10-24 12:42:23' AND '2023-04-24 12:42:23' and eventtype in ('doc.preview', 'click.resultlink*', 'click.previewlink*') skip 0 COUNT 0",
    attributes: {
      cachehit: "0",
      rowfetchtime: "0.02 ms",
      processingtime: "22.32 ms",
      matchingrowcount: "8565",
      postgroupbymatchingrowcount: "8565",
    },
  },
  $aggregationMap: {
    collection: {
      name: "collection",
      column: "collection",
      items: [
        {
          value: "/I_NS1_Tools/I_Jira_Product/",
          count: 2017,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_Product/",
        },
        {
          value: "/I_NS2_Google/I_GoogleDrives_official/",
          count: 953,
          $filtered: false,
          display: "/I_NS2_Google/I_GoogleDrives_official/",
        },
        {
          value: "/I_Google/I_GoogleDrives/",
          count: 951,
          $filtered: false,
          display: "/I_Google/I_GoogleDrives/",
        },
        {
          value: "/I_NS1_Tools/I_Loopio/",
          count: 764,
          $filtered: false,
          display: "/I_NS1_Tools/I_Loopio/",
        },
        {
          value: "/I_Extranet/I_CustomerSupport/",
          count: 583,
          $filtered: false,
          display: "/I_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Extranet/I_Overflow/",
          count: 536,
          $filtered: false,
          display: "/I_NS1_Extranet/I_Overflow/",
        },
        {
          value: "/I_NS1_Tools/I_Slack/",
          count: 493,
          $filtered: false,
          display: "/I_NS1_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 294,
          $filtered: false,
          display: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Tools/I_Confluence/",
          count: 258,
          $filtered: false,
          display: "/I_NS1_Tools/I_Confluence/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport/",
          count: 224,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 184,
          $filtered: false,
          display: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_Doc/",
          count: 168,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_Doc/",
        },
        {
          value:
            "/I_NS1_Extranet/I_filesystem_madcap_flare_only_api_net_FTP/",
          count: 152,
          $filtered: false,
          display:
            "/I_NS1_Extranet/I_filesystem_madcap_flare_only_api_net_FTP/",
        },
        {
          value: "/I_NS1_Internet/I_Github_doc_sba_angular/",
          count: 134,
          $filtered: false,
          display: "/I_NS1_Internet/I_Github_doc_sba_angular/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_SBA/",
          count: 101,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_SBA/",
        },
        {
          value: "/I_Tools/I_Github/",
          count: 86,
          $filtered: false,
          display: "/I_Tools/I_Github/",
        },
        {
          value: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide/",
          count: 79,
          $filtered: false,
          display: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide/",
        },
        {
          value: "/I_NS1_Internet/I_Sinequa/",
          count: 74,
          $filtered: false,
          display: "/I_NS1_Internet/I_Sinequa/",
        },
        {
          value: "/I_NS1_Google/I_GoogleDrives/",
          count: 68,
          $filtered: false,
          display: "/I_NS1_Google/I_GoogleDrives/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_QA/",
          count: 45,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_QA/",
        },
        {
          value: "/I_Archives/Prospects/",
          count: 40,
          $filtered: false,
          display: "/I_Archives/Prospects/",
        },
        {
          value: "/I_NS1_Intranet/I_Impact/",
          count: 37,
          $filtered: false,
          display: "/I_NS1_Intranet/I_Impact/",
        },
        {
          value: "/I_Extranet/I_University_Courses/",
          count: 26,
          $filtered: false,
          display: "/I_Extranet/I_University_Courses/",
        },
        {
          value: "/I_Salesforce/I_Opportunities/",
          count: 24,
          $filtered: false,
          display: "/I_Salesforce/I_Opportunities/",
        },
        {
          value: "/I_Archives/Customers/",
          count: 20,
          $filtered: false,
          display: "/I_Archives/Customers/",
        },
        {
          value: "/I_NS1_Intranet/I_SBA_github_Internal/",
          count: 20,
          $filtered: false,
          display: "/I_NS1_Intranet/I_SBA_github_Internal/",
        },
        {
          value: "/I_Salesforce/I_Accounts/",
          count: 16,
          $filtered: false,
          display: "/I_Salesforce/I_Accounts/",
        },
        {
          value: "/I_Apps/I_Training/",
          count: 16,
          $filtered: false,
          display: "/I_Apps/I_Training/",
        },
        {
          value: "/I_Competitors/Lucidworks.web/",
          count: 13,
          $filtered: false,
          display: "/I_Competitors/Lucidworks.web/",
        },
        {
          value: "/I_Competitors/IHSMarkit.web/",
          count: 12,
          $filtered: false,
          display: "/I_Competitors/IHSMarkit.web/",
        },
        {
          value: "/I_Archives/AvantVente/",
          count: 12,
          $filtered: false,
          display: "/I_Archives/AvantVente/",
        },
        {
          value: "/I_NS2_Tools/I_Slack/",
          count: 10,
          $filtered: false,
          display: "/I_NS2_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Extranet/I_Download.sinequa.com_Azure/",
          count: 10,
          $filtered: false,
          display: "/I_NS1_Extranet/I_Download.sinequa.com_Azure/",
        },
        {
          value: "/I_Extranet/I_University_Users/",
          count: 9,
          $filtered: false,
          display: "/I_Extranet/I_University_Users/",
        },
        {
          value: "/I_NS1_Tools/I_Jira_IT/",
          count: 9,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_IT/",
        },
        {
          value: "/I_Archives/MS/",
          count: 9,
          $filtered: false,
          display: "/I_Archives/MS/",
        },
        {
          value: "/I_Competitors/twitter/",
          count: 9,
          $filtered: false,
          display: "/I_Competitors/twitter/",
        },
        {
          value: "/I_NS1_Extranet/I_PartnerCorner/",
          count: 8,
          $filtered: false,
          display: "/I_NS1_Extranet/I_PartnerCorner/",
        },
        {
          value: "/I_NS1_Video/I_Vimeo/",
          count: 8,
          $filtered: false,
          display: "/I_NS1_Video/I_Vimeo/",
        },
        {
          value: "/I_Salesforce/I_Projects/",
          count: 8,
          $filtered: false,
          display: "/I_Salesforce/I_Projects/",
        },
        {
          value: "/I_Extranet/I_CustomerSupport_GDPR_only/",
          count: 7,
          $filtered: false,
          display: "/I_Extranet/I_CustomerSupport_GDPR_only/",
        },
        {
          value: "/I_Intranet/I_Company_Facebook/",
          count: 6,
          $filtered: false,
          display: "/I_Intranet/I_Company_Facebook/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport_GDPR_only/",
          count: 5,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport_GDPR_only/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport/[",
          count: 5,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport/[",
        },
        {
          value: "/I_NS2_Tools/I_Jira_Doc/",
          count: 5,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_Doc/",
        },
        {
          value: "/I_Extranet/I_ADFS/",
          count: 5,
          $filtered: false,
          display: "/I_Extranet/I_ADFS/",
        },
        {
          value: "/I_NS2_Tools/I_Jira_SBA/",
          count: 5,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_SBA/",
        },
        {
          value: "/I_Salesforce/I_Contacts/",
          count: 5,
          $filtered: false,
          display: "/I_Salesforce/I_Contacts/",
        },
        {
          value: "/I_Salesforce/I_BusinessCases/",
          count: 4,
          $filtered: false,
          display: "/I_Salesforce/I_BusinessCases/",
        },
        {
          value: "/I_U1_NS1_Extranet/I_Overflow/",
          count: 4,
          $filtered: false,
          display: "/I_U1_NS1_Extranet/I_Overflow/",
        },
        {
          value: "/I_U1_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 4,
          $filtered: false,
          display: "/I_U1_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Competitors/Lucidworks.web/",
          count: 3,
          $filtered: false,
          display: "/I_NS1_Competitors/Lucidworks.web/",
        },
        {
          value: "/I_Salesforce/I_Partners/",
          count: 3,
          $filtered: false,
          display: "/I_Salesforce/I_Partners/",
        },
        {
          value: "/I_Salesforce/I_Subscriptions/",
          count: 3,
          $filtered: false,
          display: "/I_Salesforce/I_Subscriptions/",
        },
        {
          value: "/I_NS1_Salesforce/I_Contacts/",
          count: 2,
          $filtered: false,
          display: "/I_NS1_Salesforce/I_Contacts/",
        },
        {
          value: "/I_NS1_Extranet/I_University_Courses/",
          count: 2,
          $filtered: false,
          display: "/I_NS1_Extranet/I_University_Courses/",
        },
        {
          value: "/I_NS1_Tools/I_Github/",
          count: 2,
          $filtered: false,
          display: "/I_NS1_Tools/I_Github/",
        },
        {
          value:
            '/I_NS1_Extranet/I_CustomerSupport/[…]insight_query_ns2","text":"11.8.1.2060"}',
          count: 2,
          $filtered: false,
          display:
            '/I_NS1_Extranet/I_CustomerSupport/[…]insight_query_ns2","text":"11.8.1.2060"}',
        },
        {
          value: "/I_Extranet/I_University_Programs/",
          count: 2,
          $filtered: false,
          display: "/I_Extranet/I_University_Programs/",
        },
        {
          value: "/I_Archives/ARD/",
          count: 2,
          $filtered: false,
          display: "/I_Archives/ARD/",
        },
        {
          value: "/I_Tools/I_Slack/",
          count: 2,
          $filtered: false,
          display: "/I_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Salesforce/I_Connectors/",
          count: 1,
          $filtered: false,
          display: "/I_NS1_Salesforce/I_Connectors/",
        },
        {
          value: "/I_NS2_Tools/I_Jira_QA/",
          count: 1,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_QA/",
        },
        {
          value: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide_NF_Official/",
          count: 1,
          $filtered: false,
          display: "/I_NS1_Google/I_GoogleDrives_Slides_BySlide_NF_Official/",
        },
        {
          value: "/I_Salesforce/I_Connectors/",
          count: 1,
          $filtered: false,
          display: "/I_Salesforce/I_Connectors/",
        },
        {
          value: "/I_NS1_Salesforce/I_BusinessCases/",
          count: 1,
          $filtered: false,
          display: "/I_NS1_Salesforce/I_BusinessCases/",
        },
        {
          value: "/I_Tools/I_Jira_Product/",
          count: 1,
          $filtered: false,
          display: "/I_Tools/I_Jira_Product/",
        },
        {
          value: "/I_NS2_Tools/I_Jira_IT/",
          count: 1,
          $filtered: false,
          display: "/I_NS2_Tools/I_Jira_IT/",
        },
      ],
      formats: null,
      $cccount: 10,
      $filtered: [],
      $remainingFiltered: [],
    },
  },
};

export const mockChartResultsShortened = {
  totalrecordcount: 8565,
  aggregations: [
    {
      name: "collection",
      column: "collection",
      items: [
        {
          value: "/I_NS1_Tools/I_Jira_Product/",
          count: 2017,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_Product/",
        },
        {
          value: "/I_NS2_Google/I_GoogleDrives_official/",
          count: 953,
          $filtered: false,
          display: "/I_NS2_Google/I_GoogleDrives_official/",
        },
        {
          value: "/I_Google/I_GoogleDrives/",
          count: 951,
          $filtered: false,
          display: "/I_Google/I_GoogleDrives/",
        },
        {
          value: "/I_NS1_Tools/I_Loopio/",
          count: 764,
          $filtered: false,
          display: "/I_NS1_Tools/I_Loopio/",
        },
        {
          value: "/I_Extranet/I_CustomerSupport/",
          count: 583,
          $filtered: false,
          display: "/I_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Extranet/I_Overflow/",
          count: 536,
          $filtered: false,
          display: "/I_NS1_Extranet/I_Overflow/",
        },
        {
          value: "/I_NS1_Tools/I_Slack/",
          count: 493,
          $filtered: false,
          display: "/I_NS1_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 294,
          $filtered: false,
          display: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Tools/I_Confluence/",
          count: 258,
          $filtered: false,
          display: "/I_NS1_Tools/I_Confluence/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport/",
          count: 224,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 184,
          $filtered: false,
          display: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
      ],
      formats: null,
      $cccount: 10,
      $filtered: [],
      $remainingFiltered: [],
    },
  ],
  records: [],
  details: {
    statement:
      "select distribution('collection,ORDER=freqdesc,COUNT=100') as collection from insight_audit_index where timestamp BETWEEN '2022-10-24 12:42:23' AND '2023-04-24 12:42:23' and eventtype in ('doc.preview', 'click.resultlink*', 'click.previewlink*') skip 0 COUNT 0",
    attributes: {
      cachehit: "0",
      rowfetchtime: "0.02 ms",
      processingtime: "22.32 ms",
      matchingrowcount: "8565",
      postgroupbymatchingrowcount: "8565",
    },
  },
  $aggregationMap: {
    collection: {
      name: "collection",
      column: "collection",
      items: [
        {
          value: "/I_NS1_Tools/I_Jira_Product/",
          count: 2017,
          $filtered: false,
          display: "/I_NS1_Tools/I_Jira_Product/",
        },
        {
          value: "/I_NS2_Google/I_GoogleDrives_official/",
          count: 953,
          $filtered: false,
          display: "/I_NS2_Google/I_GoogleDrives_official/",
        },
        {
          value: "/I_Google/I_GoogleDrives/",
          count: 951,
          $filtered: false,
          display: "/I_Google/I_GoogleDrives/",
        },
        {
          value: "/I_NS1_Tools/I_Loopio/",
          count: 764,
          $filtered: false,
          display: "/I_NS1_Tools/I_Loopio/",
        },
        {
          value: "/I_Extranet/I_CustomerSupport/",
          count: 583,
          $filtered: false,
          display: "/I_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Extranet/I_Overflow/",
          count: 536,
          $filtered: false,
          display: "/I_NS1_Extranet/I_Overflow/",
        },
        {
          value: "/I_NS1_Tools/I_Slack/",
          count: 493,
          $filtered: false,
          display: "/I_NS1_Tools/I_Slack/",
        },
        {
          value: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 294,
          $filtered: false,
          display: "/I_NS1_Extranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
        {
          value: "/I_NS1_Tools/I_Confluence/",
          count: 258,
          $filtered: false,
          display: "/I_NS1_Tools/I_Confluence/",
        },
        {
          value: "/I_NS1_Extranet/I_CustomerSupport/",
          count: 224,
          $filtered: false,
          display: "/I_NS1_Extranet/I_CustomerSupport/",
        },
        {
          value: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
          count: 184,
          $filtered: false,
          display: "/I_NS1_Intranet/I_crawler_madcap_flare_en_v11_FTP/",
        },
      ],
      formats: null,
      $cccount: 10,
      $filtered: [],
      $remainingFiltered: [],
    },
  },
};

  export const mockChartAggregation = 'collection';