name: Build and deploy the SBA doc on Github Enterprise

on:
  #push:
  # branches:
  #  - develop
  # Review gh actions docs if you want to further define triggers, paths, etc
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

  # Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # build
  build:
    name: Build to GitHub Pages
    runs-on: self-hosted
    steps:
      - name: Sudo cleanup (enabled with passwordless sudo)
        run: sudo rm -rf ${{github.workspace}}/*

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm run docs:ci
      - name: Build website
        run: npm run docs:build-internal

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docusaurus/build"

  # deployemnt job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

