# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build the SBA documentation on Github Enterprise

on:
  # Runs on pushes targeting the default branch
  # push:
  #   branches: ["develop"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      - name: Sudo cleanup (enabled with passwordless sudo)
        run: sudo rm -rf ${{github.workspace}}/*

      - name: Checkout
        uses: actions/checkout@v3

      # Doc website pre-processing

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate links in markdown files
        run: node ./scripts/doc-replace-baseurl.js

      - name: Generate links in markdown files
        run: node ./scripts/doc-preprocess.js https://github.sinequa.com/CustomerSolutions/sba-internal

      - run: npm ci
      - run: npm run builddocs

      # Generate doc website with Jekyll

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./docs/_site"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
